# Generated by Django 4.2.21 on 2025-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=220)),
                ('lastname', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=220)),
                ('lastname', models.CharField(max_length=220)),
            ],
        ),
    ]
